### ISSUE TITLE
Need some help to use use this lib...

### ISSUE THREAD

**Issue by chussenot** [redcodefinal/celestine#3]
Hi hi, I'd like to port this little my stupid ruby project to crystal with a nice SVG output... 
https://github.com/chussenot/cistergraphia

In ruby I use the gem [`rasem'](https://github.com/aseldawy/rasem) to manage the SVG.

so I'm looking at your lib, but I don't really see how to use it and make an output to a SVG file for example? Will be nice to have an example of how to use it?

**Comment by chussenot** [comment]
OK there is a render function, my bad, https://github.com/redcodefinal/celestine/blob/master/src/celestine.cr#L156

**Comment by redcodefinal** [comment]
No problem @chussenot , I also recently added more docs you can generate by downloading the project, and running `crystal docs`.
